### PR TITLE
It didn't parse well number to me

### PR DESCRIPTION
**Pull request by davicente**

### CODE REVIEW

**Comment by odynvolk** [comment]
Hi there!

Thanks for the PR! A couple of things... Could you use ES6 keywords, use the same indentation as I do (I just added an .editorconfig to master) and also add a test for the problem your code change fixes?

**Comment by davicente** [comment]
Hi again :)

I researched a little bit. The problem was the language, in spanish google search the amount of searchs are shown with a different format. 
I have a PR prepared to send with the fix and the unit test, but I'm not allowed to create a new branch and upload the commit.

It you can create a branch or give some permissions I can upload it.

Regards.

**Comment by odynvolk** [comment]
Hi there!

Aha! Good find! Yes there are probably more languages that don't work correctly at the moment.

Can't you just update this PR with the new commit?

Cheers!

**Comment by davicente** [comment]
I finally could send you a PR with the changes. 
Hope it helps

**Pull request closed without merging**
